# Default values for kafkahelmdeploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

kafkaKeystoreFileName: kafka-keystore
kafkaTruststoreFileName: kafka-truststore
kafkaJaasFileName: kafka-jaas.conf
kafkaKeyPassFileName: key-password
kafkaKeystorePassFileName: keystore-password
kafkaTruststorePassFileName: truststore-password

secrets:
  kafkaKeystoreSecretName: keystore-secret-name
  kafkaTruststoreSecretName: truststore-secret-name
  kafkaKeypassSecretName: keypass-secret-name
  kafkaKeystorepassSecretName: keystorepass-secret-name
  kafkaTruststorepassSecretName: truststorepass-secret-name
  kafkaJaasSecretName: kafka-jaas-secret-name
  zookeeperJaasSecretName: zookeeper-jaas-secret-name  

metadata:
  kafka:
    name: kafka
  zookeeper:
    name: zookeeper
namespace: kafkahelm

image:
  kafka:
    repository: confluentinc/cp-kafka
    pullPolicy: Always
    tag: latest
  zookeeper:
    repository: confluentinc/cp-zookeeper
    pullPolicy: Always
    tag: latest

env:
  kafka:
    saslEnabledMechanisms: PLAIN
    saslMechanismInterBrokerProtocol: PLAIN
    securityInterBrokerProtocol: SASL_SSL
    advertisedListeners: "PLAINTEXT://ip-10-0-2-8.eu-central-1.compute.internal:30502,SASL_SSL://ip-10-0-2-8.eu-central-1.compute.internal:30503"
    brokerId: 1
    zookeeperConnect: zookeepersvc.kafkahelm.svc:2181
    listeners: PLAINTEXT://0.0.0.0:9092,SASL_SSL://0.0.0.0:9093
    offsetsTopicReplicationFactor: 1
    transactionStateLogReplicationFactor: 1
    superUsers: User:admin
    jmxPort: 5021
    listenerSecurityProtocolMap: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,SASL_SSL:SASL_SSL
    messageMaxBytes: "10000000"
    replicaFetchMaxBytes: "10100000"
    heapOpts: "-Xms1g -Xmx2g" 
    sslKeystoreType: JKS 
    sslTruststoreType: JKS
    sslKeystoreFilename: kafka-keystore
    sslTruststoreFilename: kafka-truststore
    sslClientAuth: required
    sslKeyCredentials: key-password
    sslKeystoreCredentials: keystore-password
    sslTruststoreCredentials: truststore-password 
    kafkaOpts: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka-jaas.conf
  zookeeper:
    clientPort: 2181
    initLimit: 5
    log4jRootLoglevel: INFO
    servers: 0.0.0.0:2888:3888
    serverId: 1
    syncLimit: 2
    tickTime: 2000
    extraArgs: "-Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper-jaas.conf -Dzookeeper.authProvider=org.apache.zookeeper.server.auth.SASLAuthenticationProvider"     


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  kafka:
    name: kafkasvc
    type: NodePort
    plaintextport: 9092
    saslsslport: 9093
    plaintextnodePort: 30502
    saslsslnodePort: 30503
  zookeeper:
    name: zookeepersvc
    type: NodePort
    port: 2181
    port1: 2888
    port2: 3888
    nodePort: 30501

nodeSelector: {}

tolerations: []

affinity: {}
